language: node_js

node_js:
  - 6

cache:
  directories:
    - node_modules

services:
  - docker

before_script:
  - set -e
  - docker run -id -e MONGO_USER=mirror -e MONGO_PASS=averylongpass -e MONGO_DB=mirror -p 127.0.0.1:27017:27017 --name mongo ustcmirror/mongodb:3.4
  - npm run build:test

script: npm test
