language: node_js

node_js:
  - 6

cache:
  directories:
    - node_modules

services:
  - docker

before_script:
  - set -e
  - docker run -id -p 127.0.0.1:27017:27017 --name mongo mongo:3.4
  - npm run build

script:
  - npm test
  - npm run lint
