sudo: required
language: go

services:
  - docker
  - mongodb

env:
  global:
    - NAME=yuki DEP_VERSION=0.3.2
  matrix:
    - GOOS=linux GOARCH=amd64

go:
  - stable
  - master

matrix:
  allow_failures:
    - go: master

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
install:
  - dep ensure

before_script:
  - go get github.com/stretchr/testify/assert
  - go get -u github.com/golang/lint/golint
  - docker pull ustcmirror/test
script:
  - ci/script.sh

before_deploy:
  - ci/build.sh
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: yuki-*.tar.gz
  api_key:
    secure: BQAJgKCruMRV9LhtWZxtc1wYlTp7Y6CLJFIAn6RhXLUzdtCYJ6kYFiT7ymmspR26QvwzPjRUBYXHmf+Tag+VObEZmuTjoDM9G1qgvft1mr5Fi/9UVEkkgbiZ0O84pakrjBJoR0lXEdyzlAM0tiAOZqym3KPjSfsnLv0ByZkJadcEmNj549Ts6k4RfXgX/HlCkqAwbdu4g3UW8r3+1Ai7BKUofsSRlKuHCfwG427lpsg913QUrdcgEIpXdFDUbAwRkDsYyRqGRnK4X9YvU0MySNA1sSKhBzTgXhb1rAHMq2HKa/ZIpe4Jft0OLu0ZU2hlOK1hd5zS5bRspW/wPV2jZjO+xqWnQNZALOez2Xc53m/vZ8wxipXAdsgSpB81A03Dr7ZLm7SZcVUOGoEcDjRE2RU2k/WzOJ/jP7hNKGEdRWwodzWeczKg+fP69ErolvRFnuCy5IZytYr+4B+0jMKMQsSc0s2DCulV24f8lSKalED1O/Con5zE4rp1ZDurhHNvUKSPxCTEIqlCsbwl+dsYijrb7KyadXZjl6G1QmvIAE02mkQ0y+ALrnZMnfAvLZ5OIPk4V8lBoT6p/xf1foYCRQHfhO2ImhMM0y+7cQDeHLXSDi5VWChxuwUUicNyUB3/eZoJSS8XE8t5H2QC515gs3Qs/KWB8D/5Z3e0ZJEB5i4=
  on:
    tags: true
    condition: $TRAVIS_GO_VERSION = stable
    branch: master

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
