sudo: required
language: go

services:
  - docker
  - mongodb

go:
  - 1.8
  - 1.9
  - master

before_install:
  - docker pull ustcmirror/test

before_script: go get github.com/stretchr/testify/assert

script: go test ./core ./cron ./events ./queue

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: BQAJgKCruMRV9LhtWZxtc1wYlTp7Y6CLJFIAn6RhXLUzdtCYJ6kYFiT7ymmspR26QvwzPjRUBYXHmf+Tag+VObEZmuTjoDM9G1qgvft1mr5Fi/9UVEkkgbiZ0O84pakrjBJoR0lXEdyzlAM0tiAOZqym3KPjSfsnLv0ByZkJadcEmNj549Ts6k4RfXgX/HlCkqAwbdu4g3UW8r3+1Ai7BKUofsSRlKuHCfwG427lpsg913QUrdcgEIpXdFDUbAwRkDsYyRqGRnK4X9YvU0MySNA1sSKhBzTgXhb1rAHMq2HKa/ZIpe4Jft0OLu0ZU2hlOK1hd5zS5bRspW/wPV2jZjO+xqWnQNZALOez2Xc53m/vZ8wxipXAdsgSpB81A03Dr7ZLm7SZcVUOGoEcDjRE2RU2k/WzOJ/jP7hNKGEdRWwodzWeczKg+fP69ErolvRFnuCy5IZytYr+4B+0jMKMQsSc0s2DCulV24f8lSKalED1O/Con5zE4rp1ZDurhHNvUKSPxCTEIqlCsbwl+dsYijrb7KyadXZjl6G1QmvIAE02mkQ0y+ALrnZMnfAvLZ5OIPk4V8lBoT6p/xf1foYCRQHfhO2ImhMM0y+7cQDeHLXSDi5VWChxuwUUicNyUB3/eZoJSS8XE8t5H2QC515gs3Qs/KWB8D/5Z3e0ZJEB5i4=
  on:
    tags: true

notifications:
  email: false

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg
